   # ----------------------------------------
   # MEDNA-METADATA-POSTGIS
   # ----------------------------------------
    medna-metadata-pgdb:
        restart: always
        image: postgis/postgis:12-master
        container_name: medna-metadata-pgdb
        ports:
            - '5433:5432'     # expose ports - HOST:CONTAINER
        env_file:
            - '/home/django/medna-metadata/docker/medna.env.db'
        volumes:
            - 'postgres_data:/var/lib/postgresql/data/'

   # ----------------------------------------
   # MEDNA-METADATA
   # ----------------------------------------
    medna-metadata:
        restart: always
        build:
            context: '/home/django/medna-metadata'
            dockerfile: './docker/web/Dockerfile'
        container_name: medna-metadata
        ports:
            - '8000:8000'
        env_file:
            - '/home/django/medna-metadata/docker/medna.env'
        volumes:
            - 'static_volume:/home/django/static/'
            - 'media_volume:/home/django/media/'
        depends_on:
            - medna-metadata-pgdb
   # ----------------------------------------
   # NGINX-PROXY
   # ----------------------------------------
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - 'static_volume:/home/django/static/'
      - 'media_volume:/home/django/media/'
      - 'certs:/etc/nginx/certs'
      - 'html:/usr/share/nginx/html'
      - 'vhost:/etc/nginx/vhost.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    depends_on:
      - medna-metadata

   # ----------------------------------------
   # NGINX-LETSENCRYPT
   # ----------------------------------------
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - '/home/django/medna-metadata/docker/nginx.proxycompanion.env'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'certs:/etc/nginx/certs'
      - 'html:/usr/share/nginx/html'
      - 'vhost:/etc/nginx/vhost.d'
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost: