version: '3.8'
services:
 # docker-compose up -d
 # ----------------------------------------
 # MEDNA-METADATA
 # ----------------------------------------
  medna_metadata_web:
    restart: always
    image: mkimble88/medna-metadata:latest
    container_name: medna_metadata_web
    command: /home/django/web_start.sh
    ports:
      - 8000:8000
    env_file:
      - 'medna.env'
    volumes:
      - '../:/home/django/medna-metadata/'
    depends_on:
      - medna_metadata_pgdb
      - medna_metadata_rabbitmq
  # ----------------------------------------
  # MEDNA-METADATA-POSTGIS
  # command: update-postgis.sh
  # ----------------------------------------
  medna_metadata_pgdb:
    restart: always
    image: postgis/postgis:12-master
    container_name: medna_metadata_pgdb
    ports:
      - 5432:5432     # expose ports - HOST:CONTAINER
    env_file:
      - 'medna.env.db'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
 # ----------------------------------------
 # MEDNA-METADATA-RABBITMQ
 # ----------------------------------------
  medna_metadata_rabbitmq:
    restart: always
    image: rabbitmq:3.8.29-management
    container_name: medna_metadata_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - 'medna.env'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq/'
      - 'rabbitmq_logs:/var/log/rabbitmq/'
 # ----------------------------------------
 # MEDNA-METADATA-CELERYWORKER
 # ----------------------------------------
  medna_metadata_celeryworker:
    restart: always
    image: mkimble88/medna-metadata:latest
    container_name: medna_metadata_celeryworker
    command: /home/django/celeryworker_start.sh
    env_file:
      - 'medna.env'
    volumes:
      - '../:/home/django/medna-metadata/'
    depends_on:
      - medna_metadata_pgdb
      - medna_metadata_rabbitmq
      - medna_metadata_web
 # ----------------------------------------
 # MEDNA-METADATA-CELERYBEAT
 # ----------------------------------------
  medna_metadata_celerybeat:
    restart: always
    image: mkimble88/medna-metadata:latest
    container_name: medna_metadata_celerybeat
    command: /home/django/celerybeat_start.sh
    env_file:
      - 'medna.env'
    volumes:
      - '../:/home/django/medna-metadata/'
    depends_on:
      - medna_metadata_pgdb
      - medna_metadata_rabbitmq
      - medna_metadata_web
      - medna_metadata_celeryworker
 # ----------------------------------------
 # NGINX
 # ----------------------------------------
  nginx:
    restart: always
    image: mkimble88/medna-metadata-nginx:latest
    container_name: nginx
    ports:
      - 80:8080
    env_file:
      - 'medna.env'
    volumes:
      - 'static_volume:/home/django/medna-metadata/static/'
      - 'media_volume:/home/django/medna-metadata/media/'
      - 'certs:/etc/nginx/certs'
      - 'html:/usr/share/nginx/html'
      - 'vhost:/etc/nginx/vhost.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    depends_on:
      - medna_metadata_web
volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs:
  static_volume:
  media_volume:
  certs:
  html:
  vhost: