from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import utility.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvoBiomeFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome_first_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 1st Tier')),
                ('biome_first_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 1st Tier Slug')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:00000428]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Biome 1st Tier',
                'verbose_name_plural': 'ENVO Biome 1st Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoBiomeSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome_second_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 2nd Tier')),
                ('biome_second_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 2nd Tier Slug')),
                ('biome_first_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envobiomefirst')),
                ('biome_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:00000428]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Biome 2nd Tier',
                'verbose_name_plural': 'ENVO Biome 2nd Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoBiomeThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome_third_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 3rd Tier')),
                ('biome_third_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 3rd Tier Slug')),
                ('biome_second_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envobiomesecond')),
                ('biome_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 2nd Tier')),
                ('biome_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:00000428]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Biome 3rd Tier',
                'verbose_name_plural': 'ENVO Biome 3rd Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoBiomeFourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome_fourth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 4th Tier')),
                ('biome_fourth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 4th Tier Slug')),
                ('biome_third_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envobiomethird')),
                ('biome_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 3rd Tier')),
                ('biome_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 2nd Tier')),
                ('biome_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:00000428]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Biome 4th Tier',
                'verbose_name_plural': 'ENVO Biome 4th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoBiomeFifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome_fifth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 5th Tier')),
                ('biome_fifth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 5th Tier Slug')),
                ('biome_fourth_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envobiomefourth')),
                ('biome_fourth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 4th Tier')),
                ('biome_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 3rd Tier')),
                ('biome_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 2nd Tier')),
                ('biome_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:00000428]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Biome 5th Tier',
                'verbose_name_plural': 'ENVO Biome 5th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_first_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 1st Tier')),
                ('feature_first_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 1st Tier Slug')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:01000813]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Feature 1st Tier',
                'verbose_name_plural': 'ENVO Feature 1st Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_second_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_second_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 2nd Tier Slug')),
                ('feature_first_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturefirst')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:01000813]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Feature 2nd Tier',
                'verbose_name_plural': 'ENVO Feature 2nd Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_third_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_third_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 3rd Tier Slug')),
                ('feature_second_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturesecond')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:01000813]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Feature 3rd Tier',
                'verbose_name_plural': 'ENVO Feature 3rd Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureFourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_fourth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 4th Tier')),
                ('feature_fourth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 4th Tier Slug')),
                ('feature_third_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturethird')),
                ('feature_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:01000813]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ENVO Feature 4th Tier',
                'verbose_name_plural': 'ENVO Feature 4th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureFifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_fifth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 5th Tier')),
                ('feature_fifth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 5th Tier Slug')),
                ('feature_fourth_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturefourth')),
                ('feature_fourth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 4th Tier')),
                ('feature_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:01000813]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Feature 5th Tier',
                'verbose_name_plural': 'ENVO Feature 5th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureSixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_sixth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 6th Tier')),
                ('feature_sixth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 6th Tier Slug')),
                ('feature_fifth_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturefifth')),
                ('feature_fifth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 5th Tier')),
                ('feature_fourth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 4th Tier')),
                ('feature_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:01000813]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Feature 6th Tier',
                'verbose_name_plural': 'ENVO Feature 6th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureSeventh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_seventh_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 7th Tier ')),
                ('feature_seventh_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 7th Tier Slug')),
                ('feature_sixth_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturesixth')),
                ('feature_sixth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 6th Tier')),
                ('feature_fifth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 5th Tier')),
                ('feature_fourth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 4th Tier')),
                ('feature_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(max_length=255, verbose_name='ENVO Identifier', default='[ENVO:01000813]')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'ENVO Feature 7th Tier',
                'verbose_name_plural': 'ENVO Feature 7th Tiers',
            },
        ),
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('pop2005', models.IntegerField(verbose_name='Population 2005')),
                ('fips', models.CharField(blank=True, max_length=2, verbose_name='FIPS Code')),
                ('iso2', models.CharField(max_length=2, verbose_name='2 Digit ISO')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 Digit ISO')),
                ('un', models.IntegerField(verbose_name='United Nations Code')),
                ('region', models.IntegerField(verbose_name='Region Code')),
                ('subregion', models.IntegerField(verbose_name='Sub-Region Code')),
                ('lon', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'World Border',
                'verbose_name_plural': 'World Borders',
            },
        ),
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watershed_code', models.SlugField(max_length=3, unique=True, verbose_name='Watershed Code')),
                ('watershed_label', models.CharField(max_length=255, verbose_name='Watershed Label')),
                ('huc8', models.CharField(max_length=255, verbose_name='HUC8')),
                ('states', models.CharField(max_length=255, verbose_name='States')),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Latitude (DD)')),
                ('lon', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Longitude (DD)')),
                ('area_sqkm', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Area (sqkm)')),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Area (acres)')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'Watershed',
                'verbose_name_plural': 'Watersheds',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.SlugField(max_length=1, unique=True, verbose_name='System Code')),
                ('system_label', models.CharField(max_length=255, verbose_name='System Label')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
            },
        ),
        migrations.CreateModel(
            name='FieldSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.SlugField(max_length=8, unique=True, verbose_name='Site ID')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='utility.grant')),
                ('project', models.ManyToManyField(blank=True, related_name='projects', to='utility.Project', verbose_name='Affiliated Project(s)')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.system')),
                ('watershed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.watershed')),
                ('general_location_name', models.CharField(max_length=255, verbose_name='General Location')),
                ('purpose', models.CharField(max_length=255, verbose_name='Site Purpose')),
                ('site_prefix', models.CharField(max_length=6, verbose_name='Site Prefix')),
                ('site_num', models.IntegerField(default=1)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Latitude, Longitude (DD WGS84)')),
                ('envo_biome_fifth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_fifth', to='field_site.envobiomefifth')),
                ('envo_biome_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_first', to='field_site.envobiomefirst')),
                ('envo_biome_fourth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_fourth', to='field_site.envobiomefourth')),
                ('envo_biome_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_second', to='field_site.envobiomesecond')),
                ('envo_biome_third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_third', to='field_site.envobiomethird')),
                ('envo_feature_fifth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_fifth', to='field_site.envofeaturefifth')),
                ('envo_feature_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_first', to='field_site.envofeaturefirst')),
                ('envo_feature_fourth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_fourth', to='field_site.envofeaturefourth')),
                ('envo_feature_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_second', to='field_site.envofeaturesecond')),
                ('envo_feature_seventh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_seventh', to='field_site.envofeatureseventh')),
                ('envo_feature_sixth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_sixth', to='field_site.envofeaturesixth')),
                ('envo_feature_third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_third', to='field_site.envofeaturethird')),
                ('created_by', models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Created DateTime')),
            ],
            options={
                'verbose_name': 'Field Site',
                'verbose_name_plural': 'Field Sites',
            },
        ),
    ]
